# Generated by Django 4.0 on 2021-12-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_stkpushcalls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StkPushCalls',
        ),
    ]
