# Generated by Django 4.0 on 2021-12-15 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0004_stkpushcalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='businessShortCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
