# Generated by Django 4.0 on 2021-12-15 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0005_stkpushcalls_businessshortcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stkpushcalls',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='stkpushcalls',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
