# Generated by Django 4.0 on 2021-12-15 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0006_rename_created_stkpushcalls_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='paymentStatus',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stkpushcalls',
            name='stkStatus',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
