# Generated by Django 4.0 on 2021-12-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0008_alter_stkpushcalls_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='statusReason',
            field=models.CharField(default='not know', max_length=255),
        ),
    ]
