# Generated by Django 4.0 on 2022-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0009_stkpushcalls_statusreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='txnId',
            field=models.CharField(default='1212', max_length=255),
        ),
    ]
