# Generated by Django 4.0 on 2022-01-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0010_stkpushcalls_txnid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stkpushcalls',
            options={'verbose_name': 'transaction', 'verbose_name_plural': 'STK PAYMENTS'},
        ),
        migrations.AddField(
            model_name='stkpushcalls',
            name='customerName',
            field=models.CharField(default='John Due', max_length=255),
        ),
        migrations.AddField(
            model_name='stkpushcalls',
            name='txnRefNo',
            field=models.CharField(default='QA637JAIMR', max_length=255),
        ),
    ]
