# Generated by Django 4.0 on 2022-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0011_alter_stkpushcalls_options_stkpushcalls_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='paymentStatus',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='stkStatus',
            field=models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Pending', 'Pending')], max_length=255),
        ),
    ]
