# Generated by Django 4.0 on 2022-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0013_alter_stkpushcalls_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='transactionDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
