# Generated by Django 4.0 on 2022-01-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0014_stkpushcalls_transactiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='retryTimes',
            field=models.IntegerField(default=0),
        ),
    ]
