# Generated by Django 4.0 on 2022-01-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0015_stkpushcalls_retrytimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='first_name',
            field=models.CharField(default='Nil ', max_length=255),
        ),
        migrations.AddField(
            model_name='stkpushcalls',
            name='last_name',
            field=models.CharField(default='Nil', max_length=255),
        ),
        migrations.AddField(
            model_name='stkpushcalls',
            name='middle_name',
            field=models.CharField(default='Nil', max_length=255),
        ),
    ]
