# Generated by Django 4.0 on 2022-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0017_remove_stkpushcalls_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='businessShortCode',
            field=models.CharField(max_length=255, verbose_name='Short Code'),
        ),
    ]
