# Generated by Django 4.0 on 2022-01-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0018_alter_stkpushcalls_businessshortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='accountReference',
            field=models.CharField(max_length=255, verbose_name='Paid Account'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='first_name',
            field=models.CharField(default='Nil ', max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='last_name',
            field=models.CharField(default='Nil', max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='middle_name',
            field=models.CharField(default='Nil', max_length=255, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='paymentStatus',
            field=models.CharField(default='Pending', max_length=255, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='phoneNumber',
            field=models.CharField(max_length=255, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='retryTimes',
            field=models.IntegerField(default=0, verbose_name='STK Retries'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='statusReason',
            field=models.CharField(default='not know', max_length=255, verbose_name='Status Reason'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='stkStatus',
            field=models.CharField(default='Failed', max_length=255, verbose_name='STK Status'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='txnId',
            field=models.CharField(default='1212', max_length=255, verbose_name='Txn Id'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='txnRefNo',
            field=models.CharField(default='Nil', max_length=255, verbose_name='Mpesa TxnId'),
        ),
    ]
