# Generated by Django 4.0 on 2022-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0019_alter_stkpushcalls_accountreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='firebase_token',
            field=models.CharField(default='123', max_length=255),
        ),
    ]
