# Generated by Django 4.0 on 2022-01-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0020_stkpushcalls_firebase_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='stkpushcalls',
            name='request_code',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='firebase_token',
            field=models.CharField(default='12345', max_length=255),
        ),
    ]
