# Generated by Django 4.0 on 2022-01-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0021_stkpushcalls_request_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='request_code',
            field=models.CharField(default='12345', max_length=255),
        ),
    ]
