# Generated by Django 4.0 on 2022-01-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0022_alter_stkpushcalls_request_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stkpushcalls',
            name='request_code',
        ),
    ]
