# Generated by Django 4.0 on 2022-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0023_remove_stkpushcalls_request_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='amount',
            field=models.CharField(default='12', max_length=255),
        ),
    ]
