# Generated by Django 4.0 on 2022-01-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0024_alter_stkpushcalls_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
