# Generated by Django 4.0 on 2022-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0025_alter_stkpushcalls_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stkpushcalls',
            name='firebase_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='middle_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='stkpushcalls',
            name='txnRefNo',
            field=models.CharField(max_length=255, null=True, verbose_name='Mpesa TxnId'),
        ),
    ]
