# This is a basic workflow to help you get started with Actions

name: CI/CD Django  and Digital Ocean

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup python3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy DigitalOcean droplet via SSH action
        uses: appleboy/scp-action@master
        env:
          HOST: ${{secrets.SSH_HOST}}
          KEY: ${{secrets.SSH_KEY}}
          USERNAME: ${{secrets.SSH_USERNAME}}
        with:
          source: "."
          target: "/var/www/python/cdci/supertap/"

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          USERNAME: ${{secrets.SSH_USERNAME }}
          KEY: ${{secrets.SSH_KEY }}

#      - name: Checkout the code
#        uses: actions/checkout@v2
#
#      - name: Install python staffs
#        run: |
#          apt-get update
#          apt-get install python3-pip python3-dev -y
#          pip3 install --upgrade pip
#          python3 -m venv venv
#
#      - name: Activate Environment
#        run:  source venv/bin/activate
#
#      - name: Run project staff
#        run: |
#          pip install -r requirements.txt
#          python3 manage.py makemigrations
#          python3 manage.py migrate
#          python3 manage.py test
#          python3 manage.py runserver 178.128.205.106:8082
#
#
